import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import React from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const OpenSans = Open_Sans({
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["italic", "normal"],
  fallback: ["Helvetica Neue", "sans-serif"],
  subsets: ["latin-ext", "latin"],
});

export const metadata: Metadata = {
  title: "Mindparents | Mental and Intellectual ",
  description: "Generated by Team Urra",
  icons: {
    icon: "/icons/mp.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        <Providers>
          {children}
          <ReactQueryDevtools
            initialIsOpen={false}
            buttonPosition="bottom-left"
          />
        </Providers>
        <Toaster
          toastOptions={{
            duration: 2000,
          }}
          position="top-right"
        />
      </body>
    </html>
  );
}
